defaultLanguage:
  id: 14
  name: Deutsch
  abbreviation: de
zoomLevel: 1.2293345062052037
mediaFiles: "mkv|avi|mp4"
basedir: /home/cid/media/DINGE/Video/Serien
filename: "{{basedir}}/{{series.name|escape}}/Staffel {{episode.season|number:2}}/S{{episode.season|number:2}}E{{episode.episode|number:2}} - {{episode.name|escape}}{{extension}}"
