api:
    baseurl: http://thetvdb.com/api/
    key: 66019AFB50EA6280

mediaFiles: 'mkv|avi|mp4'
basedir: /home/cid/Videos/renamed
filename: '{{basedir}}/{{series.name|escape}}/Staffel {{episode.season|number:2}}/{{series.name|escape}} - S{{episode.season|number:2}}E{{episode.episode|number:2}} - {{episode.name|escape}}{{extension}}'
